import { render } from '@testing-library/react';
import React, { useContext, useEffect, useState } from 'react';
import { MdArrowBackIosNew, MdArrowForwardIos } from 'react-icons/md';
import { useParams } from 'react-router-dom';
import { BlockchainContext } from '../BlockchainContext';
import { Amount, LongTimestamp, ShortWallet } from '../components/tables/Cells';
import explorer from '../lib/api';

export const BlockView = () => {
    const { block_id } = useParams();
    const blockchain = useContext(BlockchainContext);
    const [block, setBlock] = useState({
      forged: {reward: 0, fee: 0}, generator: {address:""}, transactions: 0, timestamp: {human: ""}, id: "", height: 0, previous: ""
    });
  
    const [nextBlock, setNextBlock] = useState([])
    useEffect(() => {
      explorer
        .on(blockchain)
        .core.api("blocks")
        .get(block_id)
        .then((b) => {
            setBlock(b.body.data)
            explorer
            .on(blockchain)
            .core.api("blocks")
            .all({height:b.body.data.height+1})
            .then((nb) => {
                setNextBlock(nb.body.data);
            });
        });
    }, []);
    return (
        <div className="max-w-7xl mx-auto mt-4 text-black dark:text-white">
        <div className="my-12">
                <span className="text-3xl text-black dark:text-white">
                    Block Details
                </span>
                        </div>
      <div className="rounded bg-tertiary dark:bg-dark-tertiary text-black dark:text-white p-4 divide-y-2 divide-secondary dark:divide-dark-secondary drop-shadow-sm mb-3">
        <div className="flex mb-3">
          <div className="rounded-full bg-secondary dark:bg-dark-secondary py-3 px-3">
            BL
          </div>
          <div className="ml-4">
            <span className="">Block ID</span> <br />
            <span className="text-greenish text-ellipsis overflow-hidden">{block.id}</span>
          </div>
          <div className="grow hidden sm:inline ">
          <div className="flex justify-end">
          <a href={`/ark/blocks/${block.previous}`} className="bg-secondary dark:bg-dark-secondary hover:bg-hoverish dark:hover:bg-dark-hoverish py-3 px-4 mx-1 rounded"><MdArrowBackIosNew className="text-xl" /></a>
                {nextBlock[0] && <a href={`/ark/blocks/${nextBlock[0].id}`} className="bg-secondary dark:bg-dark-secondary hover:bg-hoverish dark:hover:bg-dark-hoverish py-3 px-4 mx-1 rounded"><MdArrowForwardIos className="text-xl"/></a>}
          </div>
          </div>
        </div>
        <div className="sm:grid sm:grid-cols-3 sm:divide-x-2 sm:divide-secondary sm:dark:divide-dark-secondary">
          <div className="flex items-center pt-3">
          <div className="rounded-full bg-secondary dark:bg-dark-secondary py-3 px-3 mr-2">
            GB
          </div>
            <div  className=" pl-3">
            <span className="">Generated by</span>
            <span className="text-greenish"><ShortWallet id={block.generator.address} /></span>

            </div>
          </div>
          <div className="flex items-center pt-3 sm:pl-3">
          <div className="rounded-full bg-secondary dark:bg-dark-secondary py-3 px-3 mr-2">
            TX
          </div>
            <div className="pl-3">
            <span className="">Transactions</span><br />
            <span className="">{block.transactions}</span>
            </div>
          </div>
          <div className="flex items-center pt-3 sm:pl-3">
          <div className="rounded-full bg-secondary dark:bg-dark-secondary py-3 px-3 mr-2">
            TX
          </div>
            <div className="pl-3">
            <span className="">Rewards</span>
            <span className="text-greenish"><Amount value={block.forged.reward}/></span>
            </div>
          </div>
        </div>
      </div>
      <div className="rounded bg-tertiary dark:bg-dark-tertiary">
      <table className="w-full">
          <tbody>
            <tr className=" hover:bg-hoverish dark:hover:bg-dark-hoverish cursor-pointer even:bg-evenish dark:even:bg-dark-evenish w-full h-14 z-10">
              <td className="pl-4 w-1/4 text-center font-bold">Height: </td>{" "}
              <td>
              {block.height.toLocaleString("us")}
              </td>
            </tr>
            <tr className=" hover:bg-hoverish dark:hover:bg-dark-hoverish cursor-pointer even:bg-evenish dark:even:bg-dark-evenish w-full h-14 z-10">
              <td className="pl-4 w-1/4 text-center font-bold">Timestamp: </td>{" "}
              <td>
                <LongTimestamp value={block.timestamp.human}/>
              </td>
            </tr>
            <tr className=" hover:bg-hoverish dark:hover:bg-dark-hoverish cursor-pointer even:bg-evenish dark:even:bg-dark-evenish w-full h-14 z-10">
              <td className="pl-4 w-1/4 text-center font-bold">Fee: </td>{" "}
              <td>
              <Amount value={block.forged.fee} />
              </td>
            </tr>
            {/* <tr className=" hover:bg-hoverish dark:hover:bg-dark-hoverish cursor-pointer even:bg-evenish dark:even:bg-dark-evenish w-full h-14 z-10">
              <td className="pl-4 w-1/4 text-center font-bold">Confirmations: </td>{" "}
              <td>
                {block.confirmations}
              </td>
            </tr> */}
          </tbody>
        </table>
      </div>
    </div>
     );

  
}
export default BlockView;